
#log_level="INFO"

[testdict]
second="ha ha"

[check]
test="this is an override in pycli.toml"
another=1234

##
##
[pycli2.testdict]
this="is a test dictionary"
second="ho ho"

[slides]
screen_id=1
image_folder="C:\\"
